import sys
import os
sys.path.append(os.path.abspath("."))

DAILY_ITEM_DICT = {
    "CNVR":{
        "CNVR01":{
            "ILSP01":["OD"]
        }, 
        "CNVR02":{
            "ILSP02":["OD"]
        },
        "CNVR03":{
            "ILSP03":["Rx"]
        },
        "CNVR04":{
            "ILSP04":["Gy"]
        },
        "CNVR05":{
            "ILSP05":["By"]
        },
        "CNVR06":{
            "ILSP06":["OD"]
        },
        "CNVR07":{
            "ILSP07":["Rx"]
        },
        "CNVR08":{
            "ILSP08":["Gy"]
        },
        "CNVR09":{
            "ILSP09":["Rx"]
        },
        "CNVR10":{
            # "ILSP10":["COLOR", "THICK"]
            "ILSP10":["TK"]
        },
        "CNVR11":{
            # "ILSP11":["COLOR", "THICK"]
            "ILSP11":["By"]
        },
        "CNVR12":{
            # "ILSP12":["COLOR", "THICK"]
            "ILSP12":["Gy"]
        },
        "CNVR13":{
            # "ILSP13":["COLOR", "THICK"]
            "ILSP13":["Gy"]
        },
        "CNVR14":{
            "ILSP14":["TK"]
        },
        "CNVR15":{
            "ILSP15":["TK"]
        },
        "CNVR16":{
            "ILSP16":["TK"]
        },
        "CNVR17":{
            # "ILSP17":["COLOR", "THICK"]
            "ILSP17":["TK"]
        }
    },
    "SAMP":{
        "SAMP01":{
            "CDME01":["-"]
        },
        "SAMP02":{
            "CDME02":["-"]
        },
        "SAMP03":{
            "SPME01":["COLOR", "TRANS"]
        },
        "SAMP04":{
            "SPME02":["COLOR", "TRANS"]
        },
        "SAMP05":{
            "SUFT01":["TK"]
        },
        "SAMP06":{
            "SPME03":["COLOR", "TRANS", "Lab"],
            "CDRV01":["CD/OL"]
        },
        "SAMP07":{
            "RSME01":["-"]
        },
        "SAMP09":{
            "SUFP09":["PS"]
        },
        "SAMP10":{
            "SUFP05":["PS"],
            "SUFP10":["PS"]
        },
        "SAMP11":{
            "SPME04":["COLOR", "TRANS", "OD_H", "OD_L"]
        },
        "SAMP13":{
            "SPME05":["OD", "COLOR", "TRANS"]
        },
        "SICV02":{
            "CDRV02":["CD/OL"]
        }
    }, 
    "REPA":{
        "REPA01":{
            "RVRP02":["-"],
            "RVRP03":["-"],
            "RVRP04":["-"],
            "RVRP05":["-"],
            "RVRP06":["-"],
            "RVRP07":["-"],
            "RVRP08":["-"],
            "RVRP35":["-"],
            "RVRP36":["-"]
        },
        "REPA02":{
            "RVRP09":["-"],
            "RVRP10":["-"],
            "RVRP11":["-"],
            "RVRP12":["-"],
            "RVRP13":["-"],
            "RVRP14":["-"],
            "RVRP15":["-"],
            "RVRP34":["-"],
            "RVRP41":["-"],
            "RVRP42":["-"]
        },
        "REPA03":{
            "RVRP17":["-"],
            "RVRP18":["-"],
            "RVRP19":["-"],
            "RVRP20":["-"],
            "RVRP22":["-"],
            "RVRP23":["-"],
            "RVRP24":["-"],
            "RVRP33":["-"]
        },
        "REPA04":{
            "RVRP25":["-"],
            "RVRP26":["-"],
            "RVRP27":["-"],
            "RVRP28":["-"],
            "RVRP29":["-"],
            "RVRP30":["-"],
            "RVRP31":["-"],
            "RVRP32":["-"]
        }
    },
    "PSME":{
        "PSME01":{
            "SUFP02":["-"],
            "SUFP11":["PS"],
            "SUFP12":["PS"]
        },
        "PSME02":{
            "SUFP03":["PS"],
            "SUFP04":["PS"],
            "SUFP13":["PS"]
        },
        "PSME03":{
            "SUFP14":["PS"],
            "SUFP15":["-"],
            "SUFP16":["PS"]
        },
        "PSME04":{
            "SUFP17":["PS"],
            "SUFP18":["PS"]
        }
    }
}